"""empty message

Revision ID: 4c9162f19c89
Revises: 61f92b12c039
Create Date: 2021-12-01 05:16:58.148856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9162f19c89'
down_revision = '61f92b12c039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'article', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    # ### end Alembic commands ###
