"""article names

Revision ID: f8eaa86e56ac
Revises: 72eb7e460957
Create Date: 2021-11-30 21:31:09.954809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8eaa86e56ac'
down_revision = '72eb7e460957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'name')
    # ### end Alembic commands ###
